from .callback_data import template
from .callback_data import change_and_name
from .choise_template import choice
from .choise_template import menu_template
from .change_user_card import change_card
from .change_user_card import user_card
from .choise_cont_user import choise_cont_user
from .choise_cont_user import change_cont_user_choise
from .choise_cont_user import cont_user
from .choise_cont_user import nest_pars
from .choise_cont_user import accept_dell
